version: '3'

services:
  # Servicio de aplicación PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: laravel
        uid: 1000
    container_name: indarca-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - indarca-network

  # Servicio de Nginx
  nginx:
    image: nginx:alpine
    container_name: indarca-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - indarca-network

  # Servicio de MySQL
  db:
    image: mysql:8.0
    container_name: indarca-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-indarca}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-indarca}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - indarca-network

networks:
  indarca-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
