services:
  - type: web
    name: indarca
    env: docker
    buildCommand: ./bin/render-build.sh
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: indarca_db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql

databases:
  - name: indarca_db
    databaseName: indarca
    user: indarca_user
